export default {
  ma: "MA(Moving Average)",
  ema: "EMA(Exponential Moving Average)",
  sma: "SMA",
  boll: "BOLL(Bolinger Bands)",
  bbi: "BBI(Bull And Bearlndex)",
  sar: "SAR(Stop and Reverse)",
  vol: "VOL(Volume)",
  macd: "MACD",
  kdj: "KDJ(KDJ Index)",
  rsi: "RSI(Relative Strength Index)",
  bias: "BIAS(Bias Ratio)",
  brar: "BRAR(Sentiment Indicator)",
  cci: "CCI(Commodity Channel Index)",
  dmi: "DMI(Directional Movement Index)",
  cr: "CR(Energy Indicator)",
  psy: "PSY(Psychological Line)",
  dma: "DMA(Different of Moving Average)",
  trix: "TRIX(Triple Exponentially Smoothed Moving Average)",
  obv: "OBV(On Balance Volume)",
  vr: "VR(Volatility Volume Ratio)",
  wr: "WR(Williams %R)",
  mtm: "MTM(Momentum Index)",
  emv: "EMV(Ease of Movement Value)",
  roc: "ROC(Price Rate of Change)",
  pvt: "PVT(Price and Volume Trend)",
  ao: "AO(Awesome Oscillator)",
};
