export default () => (
  <svg className="icon-overlay" viewBox="0 0 22 22">
    <ellipse
      cx="10.5"
      cy="11.5"
      rx="1.5"
      ry="1.5"
      strokeOpacity="0"
      stroke="none"
    />
    <ellipse
      cx="17.5"
      cy="11.5"
      rx="1.5"
      ry="1.5"
      strokeOpacity="0"
      stroke="none"
    />
    <ellipse
      cx="10.5"
      cy="11.5"
      rx="7"
      ry="7"
      fillOpacity="0"
      strokeOpacity="1"
      fill="none"
      strokeWidth="1"
      stroke="currentColor"
    />
    <ellipse
      cx="10.5"
      cy="11.5"
      rx="5"
      ry="5"
      fillOpacity="0"
      strokeOpacity="1"
      fill="none"
      strokeWidth="1"
      stroke="currentColor"
    />
    <ellipse
      cx="10.5"
      cy="11.5"
      rx="3"
      ry="3"
      fillOpacity="0"
      strokeOpacity="1"
      fill="none"
      strokeWidth="1"
      stroke="currentColor"
    />
  </svg>
);
